'use client'
import {useEffect,useRef,useState} from 'react'
import maplibregl,{GeoJSONSource,Map as MLMap,Marker} from 'maplibre-gl'

type Route={id:string,name:string,geojson:any}
type User={id:string,email:string,status:string,role:string}
type P={lat:number,lng:number}
function parseGpx(xml:string){const doc=new DOMParser().parseFromString(xml,'text/xml');const tracks=[...doc.querySelectorAll('trkseg')].map(seg=>[...seg.querySelectorAll('trkpt')].map(p=>[Number(p.getAttribute('lon')),Number(p.getAttribute('lat'))])).filter(x=>x.length>1);const routes=[...doc.querySelectorAll('rte')].map(r=>[...r.querySelectorAll('rtept')].map(p=>[Number(p.getAttribute('lon')),Number(p.getAttribute('lat'))])).filter(x=>x.length>1);const lines=[...tracks,...routes];if(!lines.length)throw new Error('No GPX track/route points found');return {type:'FeatureCollection',features:lines.map(c=>({type:'Feature',properties:{},geometry:{type:'LineString',coordinates:c}}))}}
export default function AdminClient(){const [users,setUsers]=useState<User[]>([]),[routes,setRoutes]=useState<Route[]>([]),[points,setPoints]=useState<P[]>([]),[manuals,setManuals]=useState<any[]>([]),[full,setFull]=useState(false),[msg,setMsg]=useState('');const div=useRef<HTMLDivElement>(null),map=useRef<MLMap|null>(null),hydrants=useRef<any>(null),pickMarkers=useRef<Marker[]>([])
 const loadUsers=async()=>{const r=await fetch('/api/admin/users');if(r.ok)setUsers((await r.json()).data||[])}
 const loadRoutes=async()=>{const r=await fetch('/api/routes');if(r.ok)setRoutes((await r.json()).data||[])}
 const loadHyd=async()=>{const r=await fetch('/api/hydrants',{cache:'no-store'});if(!r.ok)return;const j=await r.json();hydrants.current=j;setManuals((j.features||[]).filter((f:any)=>f.properties?.manual));const s=map.current?.getSource('hydrants') as GeoJSONSource|undefined;s?.setData(j)}
 useEffect(()=>{loadUsers();loadRoutes()},[])
 useEffect(()=>{if(!div.current||map.current)return;const m=new maplibregl.Map({container:div.current,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[-106.67,52.1332],zoom:12});map.current=m;m.addControl(new maplibregl.NavigationControl(),'bottom-right');m.on('load',()=>{m.addSource('hydrants',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'manual-ring',type:'circle',source:'hydrants',filter:['==',['get','manual'],true],paint:{'circle-radius':8,'circle-color':'#ffd400'}});m.addLayer({id:'all-hydrants',type:'circle',source:'hydrants',paint:{'circle-radius':5,'circle-color':'#d40000','circle-stroke-width':1,'circle-stroke-color':'#fff'}});m.addSource('picks',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'picks',type:'circle',source:'picks',paint:{'circle-radius':7,'circle-color':'#1677ff','circle-stroke-width':2,'circle-stroke-color':'#fff'}});loadHyd()});m.on('click',e=>setPoints(ps=>[...ps,{lat:e.lngLat.lat,lng:e.lngLat.lng}]));return()=>m.remove()},[])
 useEffect(()=>{const s=map.current?.getSource('picks') as GeoJSONSource|undefined;s?.setData({type:'FeatureCollection',features:points.map((p,i)=>({type:'Feature',properties:{n:i+1},geometry:{type:'Point',coordinates:[p.lng,p.lat]}}))} as any);pickMarkers.current.forEach(m=>m.remove());pickMarkers.current=[];if(map.current){points.forEach((p,i)=>{const el=document.createElement('div');el.className='pick-number';el.textContent=String(i+1);pickMarkers.current.push(new maplibregl.Marker({element:el}).setLngLat([p.lng,p.lat]).addTo(map.current!))})}},[points])
 useEffect(()=>{setTimeout(()=>map.current?.resize(),50)},[full])
 const setStatus=async(id:string,status:string)=>{await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});loadUsers()}
 const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const geojson=parseGpx(await f.text());const name=prompt('Route name',f.name.replace(/\.gpx$/i,''))?.trim();if(!name)return;const r=await fetch('/api/routes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,geojson,sort_order:routes.length})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMsg('Route uploaded.');loadRoutes()}catch(err:any){setMsg(err.message)}}
 const delRoute=async(id:string)=>{if(!confirm('Delete this route?'))return;await fetch('/api/routes',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});loadRoutes()}
 const move=async(i:number,d:number)=>{const a=[...routes],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setRoutes(a);await fetch('/api/routes',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({items:a.map(x=>({id:x.id}))})})}
 const addHyd=async()=>{if(!points.length)return;const r=await fetch('/api/manual-hydrants',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({points})});const j=await r.json();if(!r.ok)return setMsg(j.error||'Failed');setPoints([]);setMsg('Manual hydrants added.');loadHyd()}
 const deleteManual=async(id:string)=>{if(!confirm('Delete this manual hydrant?'))return;await fetch('/api/manual-hydrants',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});loadHyd()}
 return <main className="admin-wrap"><div className="admin-grid"><div className="row"><button onClick={()=>location.href='/'}>← Map</button><h1>Admin</h1></div>{msg&&<div className="panel">{msg}</div>}
 <section className="panel"><h2>Users</h2>{users.map(u=><div className="user-row" key={u.id}><div><b>{u.email}</b><div className="muted">{u.status} · {u.role}</div></div><div className="row"><button onClick={()=>setStatus(u.id,'approved')}>Approve</button><button onClick={()=>setStatus(u.id,'pending')}>Pending/Revoke</button><button onClick={()=>setStatus(u.id,'blocked')}>Block/Deny</button></div></div>)}</section>
 <section className="panel"><h2>GPX routes</h2><input type="file" accept=".gpx,application/gpx+xml" onChange={upload}/>{routes.map((r,i)=><div className="user-row" key={r.id}><b>{r.name}</b><div className="row"><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><button onClick={()=>delRoute(r.id)}>Delete</button></div></div>)}</section>
 <section className="panel"><h2>Manual hydrants</h2><p className="muted">Red = existing hydrants. Yellow outline = admin-added. Tap multiple missing locations; new picks are blue.</p><div className={'picker '+(full?'fullscreen':'')} ref={div}><div className="picker-actions"><button onClick={()=>setFull(v=>!v)}>{full?'Exit full screen':'Full screen'}</button><button onClick={()=>setPoints(p=>p.slice(0,-1))}>Undo</button><button onClick={()=>setPoints([])}>Clear</button><button onClick={addHyd}>Add {points.length||''}</button></div></div>{manuals.length>0&&<div><h3>Admin-added hydrants</h3>{manuals.map((f:any)=><div className="user-row" key={f.properties.id}><span>{Number(f.geometry.coordinates[1]).toFixed(6)}, {Number(f.geometry.coordinates[0]).toFixed(6)}</span><button onClick={()=>deleteManual(f.properties.id)}>Delete</button></div>)}</div>}</section>
 </div></main>}
