'use client'
import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import maplibregl,{GeoJSONSource,Map as MLMap,Marker} from 'maplibre-gl'
import {createClient} from '@/lib/supabase/client'

type Pt=[number,number]
type Segment=Pt[]
type SharedRoute={id:string,name:string,geojson:any,sort_order:number}
type PrivateRoute={id:string,name:string,segments:Segment[]}
type Mode='drive'|'route'|'new'|null
type Draft={version:1;mode:Exclude<Mode,null>;active:boolean;paused:boolean;followLocked:boolean;selectedRouteId?:string;selectedPrivate?:boolean;segments:Segment[];updatedAt:string}

function lineFeature(segments:Segment[],colorKind:'planned'|'trace'){return {type:'FeatureCollection',features:segments.filter(s=>s.length>1).map((coords,i)=>({type:'Feature',properties:{i,colorKind},geometry:{type:'LineString',coordinates:coords}}))}}
function geoToSegments(g:any):Segment[]{if(!g)return[];if(g.type==='FeatureCollection')return g.features.flatMap((f:any)=>geoToSegments(f));if(g.type==='Feature')return geoToSegments(g.geometry);if(g.type==='LineString')return [g.coordinates];if(g.type==='MultiLineString')return g.coordinates;return[]}
function boundaryTheme(){const h=new Date().getHours();return h>=19||h<7?'night':'day'}
function nextBoundary(){const n=new Date();const d=new Date(n);if(n.getHours()<7)d.setHours(7,0,0,0);else if(n.getHours()<19)d.setHours(19,0,0,0);else{d.setDate(d.getDate()+1);d.setHours(7,0,0,0)}return d.getTime()}

export default function MapClient({isAdmin,userId}:{isAdmin:boolean,userId:string}){
 const mapDiv=useRef<HTMLDivElement>(null),map=useRef<MLMap|null>(null),arrow=useRef<Marker|null>(null),watch=useRef<number|null>(null),wake=useRef<any>(null),hydrantEpoch=useRef(0),hydrantTimer=useRef<any>(null),lastServerSync=useRef(0),syncPromise=useRef<Promise<void>|null>(null)
 const segmentsRef=useRef<Segment[]>([]),modeRef=useRef<Mode>(null),pausedRef=useRef(false),followRef=useRef(true),selectedRef=useRef<{id?:string,private?:boolean}>({})
 const [menu,setMenu]=useState(false),[status,setStatus]=useState('Tap a street or address to find its block.'),[theme,setTheme]=useState<'day'|'night'>(boundaryTheme()),[manualUntil,setManualUntil]=useState(0)
 const [hydrants,setHydrants]=useState(false),[shared,setShared]=useState<SharedRoute[]>([]),[privateRoutes,setPrivateRoutes]=useState<PrivateRoute[]>([]),[selected,setSelected]=useState(''),[mode,setMode]=useState<Mode>(null),[paused,setPaused]=useState(false),[followLocked,setFollowLocked]=useState(true),[unsaved,setUnsaved]=useState(false),[saveName,setSaveName]=useState('')
 const supabase=useMemo(()=>createClient(),[]),LOCAL=useMemo(()=>`sbf-drive-draft-v1:${userId}`,[userId])
 const drawTrace=useCallback(()=>{const s=map.current?.getSource('drive-trace') as GeoJSONSource|undefined;s?.setData(lineFeature(segmentsRef.current,'trace') as any)},[])
 const clearTrace=useCallback(()=>{segmentsRef.current=[];drawTrace()},[drawTrace])
 const draftNow=useCallback((active=true):Draft|null=>{if(!modeRef.current)return null;return {version:1,mode:modeRef.current,active,paused:pausedRef.current,followLocked:followRef.current,selectedRouteId:selectedRef.current.id,selectedPrivate:selectedRef.current.private,segments:segmentsRef.current,updatedAt:new Date().toISOString()}},[])
 const saveDraft=useCallback(async(force=false,active=true)=>{const d=draftNow(active);if(!d)return;localStorage.setItem(LOCAL,JSON.stringify(d));const now=Date.now();if(!force&&now-lastServerSync.current<5000)return;lastServerSync.current=now;const p=fetch('/api/drive-drafts',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(d)}).then(()=>{}).catch(()=>{});syncPromise.current=p;await p},[draftNow])
 const deleteDraft=useCallback(async()=>{localStorage.removeItem(LOCAL);await fetch('/api/drive-drafts',{method:'DELETE'}).catch(()=>{})},[])
 const requestWake=useCallback(async()=>{try{if('wakeLock'in navigator&&document.visibilityState==='visible'){try{await wake.current?.release?.()}catch{};wake.current=await (navigator as any).wakeLock.request('screen')}}catch{}},[])
 const loadRoutes=useCallback(async()=>{const [a,b]=await Promise.all([fetch('/api/routes'),fetch('/api/driven-routes')]);if(a.ok)setShared((await a.json()).data||[]);if(b.ok)setPrivateRoutes((await b.json()).data||[])},[])

 useEffect(()=>{if(!mapDiv.current||map.current)return;const m=new maplibregl.Map({container:mapDiv.current,style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[-106.67,52.1332],zoom:13,dragRotate:true,touchPitch:false});map.current=m;m.addControl(new maplibregl.NavigationControl({showCompass:false,showZoom:true}),'bottom-right');m.on('load',()=>{m.addSource('planned-route',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'planned-route',type:'line',source:'planned-route',paint:{'line-color':'#e00000','line-width':5}});m.addSource('drive-trace',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'drive-trace',type:'line',source:'drive-trace',paint:{'line-color':'#1677ff','line-width':5}});m.addSource('hydrants',{type:'geojson',data:{type:'FeatureCollection',features:[]}});m.addLayer({id:'hydrants-manual-ring',type:'circle',source:'hydrants',filter:['==',['get','manual'],true],paint:{'circle-radius':7,'circle-color':'#ffd400'}});m.addLayer({id:'hydrants-city',type:'circle',source:'hydrants',paint:{'circle-radius':5,'circle-color':'#d60000','circle-stroke-width':1,'circle-stroke-color':'#fff'}})});m.on('click',async e=>{if(modeRef.current)return;setStatus('Looking up…');try{const r=await fetch(`/api/reverse?lat=${e.lngLat.lat}&lon=${e.lngLat.lng}`);const j=await r.json();if(!r.ok)throw new Error(j.error);const a=j.address||{};const house=a.house_number?`${a.house_number} `:'';const road=a.road||a.residential||a.neighbourhood||j.display_name;setStatus(`${house}${road}`)}catch{setStatus('Address lookup failed.')}});return()=>m.remove()},[])

 useEffect(()=>{document.documentElement.classList.toggle('night',theme==='night');const t=setInterval(()=>{if(Date.now()>=manualUntil)setTheme(boundaryTheme())},60000);return()=>clearInterval(t)},[theme,manualUntil])
 useEffect(()=>{loadRoutes();requestWake();const vis=()=>{if(document.visibilityState==='visible')requestWake()};const tap=()=>requestWake();document.addEventListener('visibilitychange',vis);document.addEventListener('pointerdown',tap,{passive:true});return()=>{document.removeEventListener('visibilitychange',vis);document.removeEventListener('pointerdown',tap);try{wake.current?.release?.()}catch{}}},[loadRoutes,requestWake])
 useEffect(()=>{const t=setInterval(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.replace('/login');return}const {data:p}=await supabase.from('profiles').select('status').eq('id',user.id).single();if(!p||p.status!=='approved')window.location.replace('/login?error='+encodeURIComponent(p?.status==='blocked'?'Your account is blocked.':'Your account is no longer approved.'))},15000);return()=>clearInterval(t)},[supabase])

 const loadHydrants=useCallback(async()=>{const epoch=hydrantEpoch.current;try{const r=await fetch('/api/hydrants',{cache:'no-store'});const j=await r.json();if(epoch!==hydrantEpoch.current||!hydrants||!r.ok)return;const s=map.current?.getSource('hydrants') as GeoJSONSource|undefined;s?.setData(j)}catch{}},[hydrants])
 useEffect(()=>{clearInterval(hydrantTimer.current);if(!hydrants){hydrantEpoch.current++;const s=map.current?.getSource('hydrants') as GeoJSONSource|undefined;s?.setData({type:'FeatureCollection',features:[]});return}loadHydrants();hydrantTimer.current=setInterval(loadHydrants,15*60*1000);return()=>clearInterval(hydrantTimer.current)},[hydrants,loadHydrants])

 const setPlanned=useCallback((segs:Segment[])=>{const s=map.current?.getSource('planned-route') as GeoJSONSource|undefined;s?.setData(lineFeature(segs,'planned') as any)},[])
 useEffect(()=>{if(!selected){setPlanned([]);selectedRef.current={};return}const [kind,id]=selected.split(':');selectedRef.current={id,private:kind==='p'};const r=kind==='p'?privateRoutes.find(x=>x.id===id):shared.find(x=>x.id===id);setPlanned(kind==='p'?((r as PrivateRoute)?.segments||[]):geoToSegments((r as SharedRoute)?.geojson))},[selected,shared,privateRoutes,setPlanned])

 const startGps=useCallback((newMode:Exclude<Mode,null>,restored=false)=>{if(!navigator.geolocation){setStatus('GPS is not available.');return}modeRef.current=newMode;setMode(newMode);pausedRef.current=false;setPaused(false);followRef.current=true;setFollowLocked(true);setUnsaved(false);if(!restored)segmentsRef.current=[[]];else segmentsRef.current.push([]);drawTrace();requestWake();watch.current=navigator.geolocation.watchPosition(p=>{const lng=p.coords.longitude,lat=p.coords.latitude,heading=Number.isFinite(p.coords.heading as number)?Number(p.coords.heading):0;if(!arrow.current&&map.current){const el=document.createElement('div');el.className='gps-arrow';arrow.current=new Marker({element:el,rotationAlignment:'map'}).setLngLat([lng,lat]).addTo(map.current)}else arrow.current?.setLngLat([lng,lat]);arrow.current?.setRotation(heading||0);if(!pausedRef.current){let seg=segmentsRef.current[segmentsRef.current.length-1];if(!seg){seg=[];segmentsRef.current.push(seg)}seg.push([lng,lat]);drawTrace();saveDraft(false,true)}if(followRef.current&&map.current)map.current.easeTo({center:[lng,lat],bearing:heading||map.current.getBearing(),duration:450})},err=>setStatus(`GPS: ${err.message}`),{enableHighAccuracy:true,maximumAge:1000,timeout:15000});saveDraft(true,true)},[drawTrace,requestWake,saveDraft])
 const stopWatcher=()=>{if(watch.current!==null){navigator.geolocation.clearWatch(watch.current);watch.current=null}}
 const stopDrive=useCallback(async()=>{stopWatcher();const old=modeRef.current;modeRef.current=null;setMode(null);pausedRef.current=false;setPaused(false);followRef.current=false;setFollowLocked(false);if(old==='new'){setUnsaved(true);const d:Draft={version:1,mode:'new',active:false,paused:false,followLocked:false,segments:segmentsRef.current,updatedAt:new Date().toISOString()};localStorage.setItem(LOCAL,JSON.stringify(d));await fetch('/api/drive-drafts',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(d)}).catch(()=>{})}else{clearTrace();await deleteDraft()}},[clearTrace,deleteDraft])
 const togglePause=useCallback(()=>{if(!modeRef.current)return;pausedRef.current=!pausedRef.current;setPaused(pausedRef.current);if(!pausedRef.current)segmentsRef.current.push([]);saveDraft(true,true)},[saveDraft])
 const toggleFollow=useCallback(()=>{if(!modeRef.current)return;followRef.current=!followRef.current;setFollowLocked(followRef.current);saveDraft(true,true)},[saveDraft])

 useEffect(()=>{(async()=>{let d:Draft|null=null;try{const local=JSON.parse(localStorage.getItem(LOCAL)||'null');if(local?.version===1)d=local}catch{}try{const r=await fetch('/api/drive-drafts');if(r.ok){const j=await r.json();const server=j.data?.draft as Draft|undefined;if(server&&(!d||new Date(server.updatedAt)>new Date(d.updatedAt)))d=server}}catch{}if(!d||!d.segments?.length)return;segmentsRef.current=d.segments;drawTrace();if(d.selectedRouteId){selectedRef.current={id:d.selectedRouteId,private:d.selectedPrivate};setSelected(`${d.selectedPrivate?'p':'s'}:${d.selectedRouteId}`)}if(d.active){modeRef.current=d.mode;setMode(d.mode);pausedRef.current=false;setPaused(false);followRef.current=d.followLocked!==false;setFollowLocked(followRef.current);startGps(d.mode,true);setStatus('Recovered unfinished drive. A new trace segment was started.')}else if(d.mode==='new'){setUnsaved(true);setStatus('Recovered unsaved route. Save or discard it.')}})()},[drawTrace,startGps])

 const savePrivate=async()=>{const name=saveName.trim();if(!name)return setStatus('Enter a route name.');const r=await fetch('/api/driven-routes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,segments:segmentsRef.current})});const j=await r.json();if(!r.ok)return setStatus(j.error||'Save failed');setUnsaved(false);setSaveName('');setPlanned(segmentsRef.current);clearTrace();await deleteDraft();await loadRoutes();setSelected(`p:${j.data.id}`);setStatus('Private route saved. 🔒')}
 const discardUnsaved=async()=>{setUnsaved(false);clearTrace();await deleteDraft();setStatus('Unsaved route discarded.')}
 const startMode=(m:Exclude<Mode,null>)=>{if(m==='route'&&!selected)return setStatus('Select a route first.');clearTrace();startGps(m,false);setMenu(false)}
 const toggleTheme=()=>{setTheme(t=>t==='night'?'day':'night');setManualUntil(nextBoundary())}
 const signOut=async()=>{if(modeRef.current)await saveDraft(true,true);if(syncPromise.current)await syncPromise.current;await supabase.auth.signOut();window.location.replace('/login')}
 return <div className="map-shell">
  <div ref={mapDiv} className="map"/>
  <div className="topbar"><div className={'menu '+(menu?'open':'')}><button onClick={()=>setMenu(v=>!v)}>•••</button><div className="menu-panel">
   <select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select route</option>{shared.map(r=><option key={r.id} value={`s:${r.id}`}>{r.name}</option>)}{privateRoutes.map(r=><option key={r.id} value={`p:${r.id}`}>🔒 {r.name}</option>)}</select>
   <button onClick={()=>startMode('drive')}>Drive</button><button onClick={()=>startMode('route')}>Drive Route</button><button onClick={()=>startMode('new')}>Make New Route</button>
   <button onClick={()=>setHydrants(v=>!v)}>Hydrants: {hydrants?'ON':'OFF'}</button><button onClick={toggleTheme}>{theme==='night'?'Day':'Night'} mode</button>{isAdmin&&<button onClick={()=>location.href='/admin'}>Admin</button>}<button onClick={signOut}>Sign out</button>
  </div></div><div className="status">{status}</div></div>
  <div className="drive-controls"><button className="drive-btn stop" hidden={!mode} style={{display:mode?'block':'none'}} onClick={stopDrive}>Stop</button><button className="drive-btn pause" hidden={!mode} style={{display:mode?'block':'none'}} onClick={togglePause}>{paused?'Resume':'Pause'}</button><button className="drive-btn follow" hidden={!mode} style={{display:mode?'block':'none'}} onClick={toggleFollow}>Follow {followLocked?'🔒':'🔓'}</button></div>
  {unsaved&&<div className="savebar"><input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder="Private route name"/><button onClick={savePrivate}>Save</button><button onClick={discardUnsaved}>Discard</button></div>}
  <div className="compass"><span className="n">N</span><span className="e">E</span><span className="s">S</span><span className="w">W</span></div>
 </div>
}
